# Generated by Django 4.1.7 on 2023-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expdatetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
