# Generated by Django 4.1.7 on 2023-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_expdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expdatetime',
            new_name='expdate',
        ),
        migrations.AddField(
            model_name='expense',
            name='exptime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
