# Generated by Django 4.1.7 on 2023-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transactionType',
            field=models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=50, null=True),
        ),
    ]
