# Generated by Django 4.1.7 on 2023-04-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expense_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.payee'),
        ),
    ]
