# Generated by Django 4.1.7 on 2023-04-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_expense_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.subcategory'),
        ),
    ]
