# Generated by Django 4.1.7 on 2023-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_expense_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('creditcard', 'CreditCard'), ('google pay', 'Google Pay'), ('paytm', 'Paytm'), ('phone pay', 'Phone Pay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='subcategory',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
