# Generated by Django 4.1.7 on 2023-05-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_expense_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cid',
        ),
    ]
