# Generated by Django 4.1.7 on 2023-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transactionType',
        ),
    ]
