# Generated by Django 4.1.7 on 2023-03-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetail_remove_user_age_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='first_name',
            new_name='username',
        ),
    ]
