# Generated by Django 4.1.7 on 2023-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_first_name_userdetail_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
