# Generated by Django 4.1.7 on 2023-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_username_userdetail_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
