# Generated by Django 4.1.7 on 2023-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_email_alter_user_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
