# Generated by Django 4.1.7 on 2023-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userdetail_budget_userdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
