# Generated by Django 4.1.7 on 2023-04-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_age_user_budget_user_phone_user_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
