# Generated by Django 4.1.7 on 2023-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_budget_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media/avtar7.png', null=True, upload_to='image'),
        ),
    ]
