# Generated by Django 4.1.7 on 2023-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media/avtar7.png', null=True, upload_to='image/'),
        ),
    ]
